if(WIN32)
    set(BSCV_FOUND TRUE)
    file(GLOB libFiles_RELEASE "${CMAKE_CURRENT_LIST_DIR}/bscv/lib/Release/*.lib")
    file(GLOB dllFiles_RELEASE "${CMAKE_CURRENT_LIST_DIR}/bscv/bin/Release/*.dll")
    file(GLOB libFiles_DEBUG "${CMAKE_CURRENT_LIST_DIR}/bscv/lib/Debug/*.lib")
    file(GLOB dllFiles_DEBUG "${CMAKE_CURRENT_LIST_DIR}/bscv/bin/Debug/*.dll")
    set(BSCV_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/bscv/include CACHE STRING "BSCV_INCLUDE_DIRS" FORCE)
    set(BSCV_LIBRARYS "$<$<CONFIG:Debug>:${libFiles_DEBUG}>$<$<CONFIG:Release>:${libFiles_RELEASE}>" CACHE STRING "BSCV_LIBRARYS" FORCE)
    set(BSCV_DLLS "$<$<CONFIG:Debug>:${dllFiles_DEBUG}>$<$<CONFIG:Release>:${dllFiles_RELEASE}>" CACHE STRING "BSCV_DLLS" FORCE)
endif(WIN32)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(BSCV DEFAULT_MSG BSCV_INCLUDE_DIRS BSCV_LIBRARYS BSCV_DLLS)